export type Invoice = {
    id: string,
    object: string
    account_country: string,
    account_name: string | null,
    account_tax_ids: string | null,
    amount_due: number,
    amount_paid: number,
    amount_remaining: number,
    amount_shipping: number,
    application: string | null,
    application_fee_amount: number | null,
    attempt_count: number,
    attempted: boolean,
    auto_advance: boolean,
    automatic_tax: {
        enabled: boolean,
        status: string | null
    },
    billing_reason: string,
    charge: string,
    collection_method: string
    created: number,
    currency: string,
    custom_fields: null,
    customer: string,
    customer_address: {
        city: string | null,
        country: string,
        line1: string | null,
        line2: string | null,
        postal_code: number | null,
        state: string | null
    },
    customer_email: string,
    customer_name: string,
    customer_phone: null,
    customer_shipping: null,
    customer_tax_exempt: string,
    customer_tax_ids: [],
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: string,
    discount: null,
    discounts: [],
    due_date: number,
    ending_balance: number,
    footer: null,
    from_invoice: null,
    hosted_invoice_url: string,
    invoice_pdf: string,
    last_finalization_error: null,
    latest_revision: null,
    lines: {
        object: string,
        data: [
            {
                id: string,
                object: string,
                amount: number,
                amount_excluding_tax: number,
                currency: string,
                description: string,
                discount_amounts: [],
                discountable: boolean,
                discounts: [],
                invoice_item: string,
                livemode: boolean,
                metadata: {},
                period: {
                    end: number,
                    start: number
                },
                plan: null,
                price: {
                    id: string,
                    object: string,
                    active: boolean,
                    billing_scheme: string,
                    created: number,
                    currency: string,
                    custom_unit_amount: null,
                    livemode: boolean,
                    lookup_key: null,
                    metadata: {},
                    nickname: null,
                    product: string,
                    recurring: null,
                    tax_behavior: string,
                    tiers_mode: null,
                    transform_quantity: null,
                    type: string,
                    unit_amount: number,
                    unit_amount_decimal: number
                },
                proration: boolean,
                proration_details: {
                    credited_items: null
                },
                quantity: 1,
                subscription: null,
                tax_amounts: [],
                tax_rates: [],
                type: string,
                unit_amount_excluding_tax: number
            }
        ],
        has_more: boolean,
        total_count: number,
        url: string
    },
    livemode: boolean,
    metadata: {
        orderId: number
    },
    next_payment_attempt: null,
    number: string,
    on_behalf_of: null,
    paid: boolean,
    paid_out_of_band: boolean,
    payment_intent: string,
    payment_settings: {
        default_mandate: null,
        payment_method_options: null,
        payment_method_types: null
    },
    period_end: number,
    period_start: number,
    post_payment_credit_notes_amount: number,
    pre_payment_credit_notes_amount: number,
    quote: null,
    receipt_number: string,
    rendering_options: null,
    shipping_cost: null,
    shipping_details: null,
    starting_balance: number,
    statement_descriptor: null,
    status: string,
    status_transitions: {
        finalized_at: number,
        marked_uncollectible_at: null,
        paid_at: number,
        voided_at: null
    },
    subscription: null,
    subtotal: number,
    subtotal_excluding_tax: number,
    tax: null,
    test_clock: null,
    total: number,
    total_discount_amounts: [],
    total_excluding_tax: number,
    total_tax_amounts: [],
    transfer_data: null,
    webhooks_delivered_at: number
}