name: Release
on:
  push:
    branches:
      - main

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Setup Node
        uses: actions/setup-node@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: 18
      - name: install dependencies
        run: npm i

  semantic-release:
    runs-on: ubuntu-latest
    needs: [install-deps]
    steps:
      - uses: actions/checkout@v3
        name: Checkout main
        with:
          fetch-depth: 0
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Launch Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
